# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'HogwartsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HogwartsApp

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Alamofire', '~> 5.2'

  target 'HogwartsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HogwartsAppUITests' do
    # Pods for testing
  end

end
